# Etapa 1: Build de Angular
FROM node:22-alpine AS build

# Carpeta de trabajo
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar todo el proyecto
COPY . .

# Compilar Angular en modo producción
RUN npm run build

# Etapa 2: Servidor Nginx
FROM nginx:alpine

# Copiar build generado
COPY --from=build /app/dist/serviclick-frontend/browser /usr/share/nginx/html

# Exponer puerto 80
EXPOSE 80

# Iniciar nginx
CMD ["nginx", "-g", "daemon off;"]