sonar.projectKey=ServiClick-Frontend
sonar.projectName=ServiClick Frontend
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/.angular/**,**/coverage/**,**/*.spec.ts,**/logs/**,**/cypress/**,**/environments/**,**/client-topbar/**,**/vendor-topbar/**,**/mapa/**,**/select-role/**,src/main.ts,src/app/app.routes.ts,src/app/app.config.ts
sonar.javascript.lcov.reportPaths=coverage/serviclick-frontend/lcov.info
